### ISSUE TITLE
CovidWOBPDF Folder Unreachable

### ISSUE THREAD

**Issue by seryafarma** [seryafarma/Freedom-of-Information-Act-Collections#1]
At the moment I can't download the CovidWOBPDF folder. It keeps showing me the busy icon even after 1 hour waiting. @maartenmarx , is there any other way to download the folder?

**Comment by maartenmarx** [comment]
Hi @seryafarma ,

That folder was crazy big. Zippoing it also took 22 Gb and i cannot sent that by wetransfer.,
I have chopped it up and placed it in DocumentPslitting/data on surfdrive with this readme
So I hope onec it is synced you can get the data easier step by step.

Otherwise, lets see how to do this. 
I you have any good ideas, please let me know.

cheers
maarten


# readme

* This directiory contains all data.

See the folder ProbeerselsBy Marx for notebooks used to create this dataset.

## PDFs

* all original pdfs

### XMLs

* xml output from `pdftohtml -xml` ran on the pdfs

### JPG_andPNG

* images created by pdftohtml

### OCRedimages.zip

* output from running tessaract on the JPG and PNG images

**Comment by seryafarma** [comment]
Hi @maartenmarx ,

If you use 7zip you can also split it based on size. There is a 1000MB option there which will split the folder of 1 file = 1 GB each. (I am using an example of tesseract binary)

![image](https://user-images.githubusercontent.com/3274071/146768462-66d8be79-3bc5-46b5-afff-1a040fbf6831.png)

**The results would look like this:**
![image](https://user-images.githubusercontent.com/3274071/146768592-244b82ca-9cd9-4133-99ea-72f80d7739df.png)

Maybe this will be easier to be downloaded from surfdrive?

**Comment by maartenmarx** [comment]
You should be able to see something inside the dfata folder right now. It is syncing the rest.
Lets wait for that. I used zip from linux command line, so must check that option.
@seryafarma

**Comment by seryafarma** [comment]
Let's wait indeed, I think in linux you can simply use `tar` option as well. Now that you mention it, I notice that using linux in this project can make it simpler than windows. For example to install the libraries and dependencies, it was way easier in ubuntu. I did some prototype based on Tesseract on an ubuntu VM. Which linux distribution do you use @maartenmarx? Maybe easier also if I use a dedicated linux machine for this (instead of a VM).

Is this the `pdftohtml` that you are using: https://linux.die.net/man/1/pdftohtml

Was this the way you preprocess the documents?
- Download the original pdf from WOB website.
- Use pdftohtml to get png files and xml.
- Use tesseract to access the content of the png files from the previous step.

I have not tried `pdftohtml`, I only noticed that tesseract needs a png file to process and it can't work with pdf file directly.

**Comment by maartenmarx** [comment]
Hi @seryafarma ,

I followed your advice and used linux split. Now all pDFs and xml are on surfdrive and it is tonite uploading one by one these smalls parts of the ocred jpg's and png's. I thionk tomorrow you have all.

### preprocess

* yes exactly, see the notrebooks, also pdftohtml creates both png and jpg files, no idea why. But you see that in the XML.
* Sometimes it seems to always create 12 jpgs per page. Often there is nothing on it.... 
* You will also see that the tesseract OCR is often empty.

### put back together

* If you can find the way to put the "files" back together, eg at page level, that would be great. 
* At least we can then make a "good" bag of words of each page.  (even though I am not sure that helps for the splitting....)

* Good luck!!

**Comment by maartenmarx** [comment]
### putting the files back together again

* see <https://unix.stackexchange.com/questions/24630/whats-the-best-way-to-join-files-again-after-splitting-them>

**Comment by seryafarma** [comment]
Thanks @maartenmarx , I am now downloading the files. I seem to be able to get the `data/` in my drive. The folder `CovidWOBPDFs` is still not responding to download though.

By the way, I am wondering how people are doing the document splitting at the moment? Do they split the document manually? Do they use some automation to be able to split the documents? Do they outsource this task to a 3rd party to split?

**Comment by maartenmarx** [comment]
Hi @seryafarma ,

cheers, but all is now in that data folder.

I don;t know how they split now. If at all. Maybe they simply search with cntrl F, or split by page and have a search engine?

They told me they have some trick based on regex, but they are afraid it breaks for another collection right away.

Once we have some results we can go and have a look, or do a zoom meeting.

**Comment by seryafarma** [comment]
Hi @maartenmarx good afternoon. This works, I am able to get all the files now 🎉. 
Thanks! I will close this issue related to getting the data. 

Your link on putting back files together with `cat` also works nicely!

**Comment by maartenmarx** [comment]
Ah nice I am happy to hear thyat. Keep me upxdated! @seryafarma
