### ISSUE TITLE
Research Question

### ISSUE THREAD

**Issue by seryafarma** [seryafarma/Freedom-of-Information-Act-Collections#11]
Hi @maartenmarx ,

For this thesis I was thinking about the **research question**. In the draft thesis design I put the questions as follows:

1. Can deep learning be utilized to make an automated system to split WOB COVID-19 documents?

This question has more **sub questions**, which is coming from the data that we have:

1. What features from the document can be used to help splitting?
2. Does Dutch language have any influence in the splitting performance?
3. What is the effect of censorship to the splitting performance?

I am not very sure about the questions above actually. What do you think about it?

**Comment by maartenmarx** [comment]
Hi @seryafarma 

Thanks for your questions. I am strict and harsh with you: these questions will not help you or a reader to guide yor work.
The answer to your main question is likely: yes, if you have enough data. 

Please for your subquestions think of the shaope of the answer.

Anyway, I would keep the main question more open for ML techniques, and even allow a rule based system. 
For now, we are happy if we get something working! 

The questions will come by them self. State very very basic ones in your notebooks.

good luck!!

**Comment by seryafarma** [comment]
Hi @maartenmarx , yes thanks for being strict and clear.
I still don't have any research question yet in mind, but as you say they will come by itself. Maybe after I do some EDA I can have some more clarity.

I have another question maybe you can help.
In datanose I have to submit some information for the Thesis form, can you help me with this?

The information boxes are as follows:

### Working Title
Something like: _Automatic WOB Document Splitting_ ?
### UvA Supervisor
dr. Maarten Marx
### Daily mentor
I should also put your name here, right?
### Institute and department/research group
Please indicate the main location of the work on your project.

What should I put here? Should I put: _University of Amsterdam - IRLab_ ?

### Project Description
Do you also have a project description I can upload?

### Timetable
The start should be in January, right?

Best regards, 
Fajar

**Comment by maartenmarx** [comment]
Hi @seryafarma ,

yes, all your guessed answers are right. Just use the project description that attracted you to this project!

**Comment by seryafarma** [comment]
Hi @maartenmarx I will close this issue and move the research question in the discussions in this github page.
