### ISSUE TITLE
PDF to HTML Usage

### ISSUE THREAD

**Issue by seryafarma** [seryafarma/Freedom-of-Information-Act-Collections#17]
Hi @maartenmarx,

What would be the usage of the `pdftohtml` ? 
For example for the file: `82493e06e956a0262e67e32167c32ff4_documenten.pdf`, it can't seem to generate proper information in the xml file. It just pops out a lot of images which are fragments of the documents. The xml file is not giving much information either.

As far as I understand, we plan to use tesseract which needs `png` files. In that case, we just need 1 png file per page to be used by tesseract, right?

**Comment by maartenmarx** [comment]
Hi fajar,

but in mst cases (75% i think) pdftohtml nicely extracts all text and data and fonts plus coordinates. So what is yopur argument against it?


Met vriendelijke groeten,

Maarten Marx

Die Philosophen haben die Welt nur verschieden interpretiert; es kömmt drauf an, sie zu verändern.

***@***.******@***.***> +31 06 400 16 120  IRlab Informatics Institute Universiteit van Amsterdam




On Jan 23, 2022, at 20:43 PM, seryafarma ***@***.******@***.***>> wrote:



Hi @maartenmarx<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmaartenmarx&data=04%7C01%7CM.J.Marx%40uva.nl%7C88a05eeb944f4b70a26908d9dea8aacb%7Ca0f1cacd618c4403b94576fb3d6874e5%7C0%7C0%7C637785638270992650%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=18BTMp18HuzN2TV32%2FvqDhXqU1SLLvw8EoqOS3UkD6w%3D&reserved=0>,

What would be the usage of the pdftohtml ?
For example for the file: 82493e06e956a0262e67e32167c32ff4_documenten.pdf, it can't seem to generate proper information in the xml file. It just pops out a lot of images which are fragments of the documents. The xml file is not giving much information either.

As far as I understand, we plan to use tesseract which needs png files. In that case, we just need 1 png file per page to be used by tesseract, right?

—
Reply to this email directly, view it on GitHub<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fseryafarma%2FFreedom-of-Information-Act-Collections%2Fissues%2F17&data=04%7C01%7CM.J.Marx%40uva.nl%7C88a05eeb944f4b70a26908d9dea8aacb%7Ca0f1cacd618c4403b94576fb3d6874e5%7C0%7C0%7C637785638270992650%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=rJIEWdoToWLRs4D0vqH1dlE2SEK%2BHj9PwFWBmfBD05Q%3D&reserved=0>, or unsubscribe<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAA4ZK4AHP3C7JWBEOOGDDP3UXRK67ANCNFSM5MTXNNRQ&data=04%7C01%7CM.J.Marx%40uva.nl%7C88a05eeb944f4b70a26908d9dea8aacb%7Ca0f1cacd618c4403b94576fb3d6874e5%7C0%7C0%7C637785638270992650%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=FQpHiPGl%2FT4WsjHsLoCkTbrcKIRWEnivb4ANF%2BT2kls%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7CM.J.Marx%40uva.nl%7C88a05eeb944f4b70a26908d9dea8aacb%7Ca0f1cacd618c4403b94576fb3d6874e5%7C0%7C0%7C637785638270992650%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=QFjgdW0LfgH7KcHx%2FuGTaX552raeCsVYQ%2Fc9tBbvkdQ%3D&reserved=0> or Android<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7CM.J.Marx%40uva.nl%7C88a05eeb944f4b70a26908d9dea8aacb%7Ca0f1cacd618c4403b94576fb3d6874e5%7C0%7C0%7C637785638270992650%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=OuaqcByHuEvmTn%2BA8jWrpzvhrUWUGN6d%2FPqbKsCvMh8%3D&reserved=0>.

**Comment by seryafarma** [comment]
Hi @maartenmarx there are two things. 

1. For the tesseract to work we need image files. If I understand correctly we wanted to use pdftohtml to generate picture files. I noticed that pdftohtml generates png and jpg file together. Not mentioning that it can have more than one image per page. This by itself is not that nice (mixing format of images, it is a bug in pdftohtml). So for this (1) I found another tool which simply convert pdf to png files one png per page. This can be used by tesseract. 

2. Getting metadata from the document such as font information and text. For this (2) also I will try to explore other options. It seems the OCR engine in pdftohtml is not that good so if presented with scanned documents it cant really pick the contents. It gives up and present them as images. I will find more example with pdftohtml pitfalls. I would suggest we find other alternative applications.

**Comment by maartenmarx** [comment]
@seryafarma , thanks!

1. Are you sure pdftohtml does OCR itself? My idea was to use it just to extract the text that **is already available in the provided PDF**. This is also an improtant thing to measure in my view (it says something on the quality of the data prfovided).
2. So please find out what (and if) OCR pdftohtml does. If you know of a better option I am happy to hear it!
3. Indeed one file per page is much better of course!! (I think pdftohtml makes many small ones because it creates an html page, and wants to have as much machin ereadable text as possible.)
4.

**Comment by seryafarma** [comment]
@maartenmarx 

I am mistaken. The pdftohtml indeed doesnt do any ocr. It only outputs text which is already stored inside the document pdf. 

https://www.mail-archive.com/poppler@lists.freedesktop.org/msg12440.html

This explains why it doesnot work with wob hand scanned documents.

**Comment by maartenmarx** [comment]
hi fajar , lets meet at 12:45 on https://uva-live.zoom.us/j/87903030392
