### ISSUE TITLE
Initial Design

### ISSUE THREAD

**Issue by seryafarma** [seryafarma/Freedom-of-Information-Act-Collections#3]
Hi @maartenmarx , 

I was thinking for the approach on splitting the document. Intuitively, if I have to manually split the document I would use the approach I draw below.

![image](https://user-images.githubusercontent.com/3274071/147421615-daecfb60-2e14-4429-bb1c-886e3e60e947.png)

Then this problem can be seen as a multiclass classification problem, and each page data + metadata can be vectorized and classified in one of the classes above. The same approach I am using in my draft thesis design.

Do you see any issue with this approach? 
This should work, right?

Also as this is a supervised learning problem then I have some work to label the documents.

**Comment by maartenmarx** [comment]
Hi @seryafarma ,

Nice idea. As you notice, you only need opening, as then the other two are defined by that. 

I suggest you try to do some handlabelling yourself, maybe together with Jackson and record the cues you use to decide that you are on a new opening page. Possibly you can first create a rule based system based on those insights.

I think that gives more insicght and value than creating vast amounts of training data.

Good luck!!

maarten

**Comment by seryafarma** [comment]
Hi @maartenmarx , first thing first.

**Happy new year!** 🎉🎉🎉
Wish this year brings you lots of happiness, success, and good health!

## Document Classes
I noticed that in the WOB documents they can be classified like this:
- Besluit
- Inventaris
- Documenten
- Others

For example here:
https://wobcovid19.rijksoverheid.nl/publicaties/2bbcec437dafabf2dc917414b37612fd/

- Do you think it is wise to have a system for each class? For example I can imagine things in _Besluit_ have different pattern than in _Documenten_ (which is very generic).
- About inventaris, do we also need to split them? or we exclude it? They normally contain a table with list of inventory (?)

## Metadata from Document
I see that along with the text, there are some other document metadata such as:

- Font type, font size.
- Images in the document.
- and maybe more metadata inside.

Do you know how can I use this metadata in my embeddings? Maybe first I should try the _text only_ approach and later with metadata included?

### Jackson
About Jackson, I saw that Jackson is included in your last mail. He also asked me to get into touch with him. Is he going to help me with this thesis project or will he make something else but related to my work also? Is he also a data science student? Should we invite him to be also a contributor here?

**Comment by maartenmarx** [comment]
Hi @seryafarma , happy new year to you tio man!! 

I answer briefly in your issue in bold.

## Document Classes
I noticed that in the WOB documents they can be classified like this:
- Besluit
- Inventaris
- Documenten
- Others

For example here:
https://wobcovid19.rijksoverheid.nl/publicaties/2bbcec437dafabf2dc917414b37612fd/

- Do you think it is wise to have a system for each class? For example I can imagine things in _Besluit_ have different pattern than in _Documenten_ (which is very generic).
- About inventaris, do we also need to split them? or we exclude it? They normally contain a table with list of inventory (?)


**As far as i understand it, inventaris contains a list of all documents of a specific WOB, so it may be  very helpful in splitting, or verifying the split. For splitting you should go for the documents, and possibkly other. I do not knwo what that is.**

## Metadata from Document
I see that along with the text, there are some other document metadata such as:

- Font type, font size.
- Images in the document.
- and maybe more metadata inside.

Do you know how can I use this metadata in my embeddings? Maybe first I should try the _text only_ approach and later with metadata included?

* **Sure, in fact I proposed to do it metadata, ie font info only, and in my notebooks you see some vectorizers which count the number of chars of each font/font size per page.**
* **I hoped that a drop in cosine similaity b etween two pages would be a good indicator of a new document: but my simple approach did not work. Check it out in this PorbeerselsMarx folder, something with vectorizeer.**
* 

### Jackson
About Jackson, I saw that Jackson is included in your last mail. He also asked me to get into touch with him. Is he going to help me with this thesis project or will he make something else but related to my work also? Is he also a data science student? Should we invite him to be also a contributor here?

* **Yes Jackson will also work on this project and possibly another student as well (who wants to do a search engine). Let's see tomorrow. I think the task is hard enough to have bioth of you have a go at it. In the first months you may haoppily work together and help each other understand thedata, make hand splits etc, but then you simply shoudl diverge.**

**Comment by seryafarma** [comment]
Issue is closed, will continue in #10
